= A Glance back at Shadowgate 64
For the last few months really on my Stream, I've been slowing hacking away at the N64 classic that is Shadowgate 64. I think now with a little distance awy from the game, it is time to take a look at what we all managed to accomplish from playing it, and what we learned. 
I cannot really look at this game in the context of other games in its genre. Traditional first person adventure games are not really ones that I play. I've poked at the original Shadowgate on the NES out of pure curiosity, but not much more than that. 

== I think lore might actually matter
The world of Shadowgate 64 is littered with books. If you've played an Elder Scrolls game, you know the drill here. The books contain lore and at times helpful information about the world. The Elder Scrolls II: Daggerfall, which came out in 1996, contains dozens of books, and while the amount available in Shadowgate 64 doesn't quite get there, it is a lot more lore delivered in this way than you would've seen in any console game I know of. Most of it revolves around the ancient hero, the villain, with hints as to the systems in the game. Puzzles will also quiz you on your knowledge in various ways, with one explicit quiz coming in the last dungeon. I cheated on that by the way. Were these tomes camples of sensational writing. Not really. What they were though, were examples of a very human touch that you don't always feel in a game. The person who developed this world seemed to really care about it and as a consequence treat it with a lot of respect. Yeah it is pretty dorky, but always endearingly so. I never really think story matters all that much in video games, but insofar as it lends to a vibe, I think Shadowgate 64's books were pretty great.

== Empty vibes
The N64 opens up worlds. In a way, it is a philosophy of game worlds that would go with Nintendo into the future, Super Mario 64 to The Legend of Zelda: Tears of the Kingdom. The Playstation and the Saturn could not renders world like the N64 could, with the closest the N64 got being Spyro. Even those stages aren't far removed from the cramped, stage-like worlds of something like Croc.  
