= A Guide to Mastering Super Mario Bros.
- Alex Konieczny
:toc: auto

== Introduction


== Ways to play
Super Mario Bros. is one of the most re-released video games of all time. Since there are countless ways to play the game, the decision about how to play come from balancing comfort, accessibility, and authenticity. The following are just a few of the methods you can choose from when playing Super Mario Bros.  

=== Nintendo Entertainment System / Nintendo Family Computer
Depending on where you live, Nintendo's first home console with interchangable games came in either the form of the Nintendo Family Computer (Famicom), if you lived in Japan, or the Nintendo Entertainment System (NES) if you lived in North America or Europe. Despite a few non-essential differences, the hardware in these systems is the same. The developers at Nintendo designed Super Mario Bros. to be played on these machines, and if you can manage to get an NES or Famicom, it can be the best way to play, though only in specific situations. Since this guide is written in English, the following instructions will specifically refer to using an NES, and the challenges that come with that version of the console.

First, the NES is around 40-years-old. Though Nintendo sold many of these systems, if is becoming more difficult, and as a result, more expesive to not only get a system, but also find the controllers and games to use with it. If avaialbilty and cost are factors, you should consider play Suepr Mario Bros. using a different method.

Second, the NES outputs its video signal using older analog formats, specifically Radio Frequencies or composite video. CRT TVs are able to handle these types of siganls best. CRT TVs are, like the NES itself, becoming more difficult to find. They also take up a lot of room and generate a lot of heat. This can be a big barrier to newer players.

You can use a newer TV, but the options

=== Nintendo Switch Online

=== Unofficial methods

==== Emualtion on PC

==== Emulation on mobile phone

==== MiSTer FPGA

== How to play

=== Story

=== Controls

=== General game mechanics

==== Objectives

==== Enemies

===== Goomba

===== Koopa Troopa

===== Piranha Plant

===== Koopa Paratroopa

===== Fire Bar

===== Podoboo

===== Cheep Cheep

===== Blooper

===== Lakitu

===== Spiny

===== Hammer Brothers

===== Buzzy Beetle

===== Bowser

==== Environment

==== Items

===== Coin

===== Mushroom

===== Fire Flower

===== Star Man

===== 1-up Mushroom

==== Secrets

===== Hidden block

===== Open Pipe

===== Beanstalk

===== Warp Zone

==== Glitches

== Advanced strategies & techniques

== Walkthrough

=== World 1

==== Stage 1-1

==== Stage 1-2

==== Stage 1-3

==== Stage 1-4

=== World 2

==== Stage 2-1

==== Stage 2-2

==== Stage 2-3

==== Stage 2-4

=== World 3

==== Stage 3-1

==== Stage 3-2

==== Stage 3-3

==== Stage 3-4

=== World 4

==== Stage 4-1

==== Stage 4-2

==== Stage 4-3

==== Stage 4-4

=== World 5

==== Stage 5-1

==== Stage 5-2

==== Stage 5-3

==== Stage 5-4

=== World 6

==== Stage 6-1

==== Stage 6-2

==== Stage 6-3

==== Stage 6-4

=== World 7

==== Stage 7-1

==== Stage 7-2

==== Stage 7-3

==== Stage 7-4

=== World 8

==== Stage 8-1

==== Stage 8-2

==== Stage 8-3

==== Stage 8-4