= The Tower of 
:toc:
:doctype: book

== Geschichte
Vor langer Zeit stand ein riesiger Turm. Niemand wusste, woher er kam. Aber wenn dieser Turm erschien, waren viele Monsters überall. Alle dachten, es hätte mit dem Turm zu tun, und Leute aus jeder Ecke der Welt kamen zu dem Turm, um ihn zu untersuchen.

Vor dem Turm stand eine große Tafel aus schwarzem Stein. Die Schrift sagte:

"60 Stufen"

Viele versuchten das Ziel zu erreichen und viele starben dabei. Dann erreichte endlich eine Gruppe von vier Abenteurern die letzte Kammer, besiegte die Finsternis, die da lebte, befreite die Leute der ganzen Welt, und fand einen kostbaren Schatz.

100 Jahre vergingen und wieder stand der Turm da. 

== Spieler 

Nur eins, wie Menschen. Könnte jeder Farbe oder art Mensch.

Jeder Mensch kann einen Helm, eine Waffe, ein Werkzeug tragen, und ein Stuck Zubehör. Er kann auch Geld und Gegenstände tragen, aber so viel wie man will. Aber wenn man stirbt, verliert man alle Rüstungen, Waffen, Werkzeuge, Gegenstände und 50% seiner Geld. Verliert man auch ein Herz. Wenn man keine Herzen mehr hat, stirbt man.

Dieser Helm bestimmt deine FLinkheit und Verteidigung. 
Dieser Waffe bestimmt deine Angriffskraft. 

== Gegenstände

=== Rüstung



== Kampfen

=== Runde
==== Bewegungen
* Angriff
* Verteidigung
* Tauschen
* Gegenstand


=== Angriff
[cols="1,1,1"]  
|===
|Vorne
|Hinten
|Beschreibung

|1
|1 
|Patzer

|2-3
|2-4
|Chip

|4-8
|5-10
|50%

|9-13
|11-15
|75%

|14-18
|16-19
|100%


|19
|20
|125%

|20
|-
|150%

|=== 

Element Verstärkung +1

=== Verteidigung
[cols="1,1,1"]  
|===
|Vorne
|Hinten
|Beschreibung

|1 
|1 
|Schrecklich

|2-4
|2-3
|0%

|5-10
|4-8
|50%

|11-15
|9-13
|75%

|16-19
|14-18
|100%

|19
|19
|Counter 50% (Vorne) +
Counter 50% (Hinten)

|20
|20 
|Counter 100% (Vorne) +
Counter 50% (Hinten)

|===

Element Verstärkung +1

== Welt

* Bergen
** Städte
*** ?
** Figuren
* Steppe
** Städte
*** Akilliat
** Figuren
* Wald
** Städte
*** Kwerkels 
** Figuren
* Tundra
** Städte
*** ?
** Figuren
* Sumpf
** Städte
*** 
** Figuren
* Hochebene 
** Städte
*** Skalla Lunat
** Figuren


== Waffen

* Schwert
* Bogen
* Stab
** Feuer
** Strom
** Eis


== Monsters
=== Marmelgellie
==== Stats
[cols="1,1"]  
|===
|KP
|10

|FH
|3

|===
==== Bewegungen
[cols="1,1"]  
|===
|Normale
|1

|Spezial
|2

|===

== Turm

* Labyrinth
* Leeres Zimmer


===

